### ISSUE TITLE
Unable to implement changes on googlefonts icons when deployed on github even though works fine when testing through localhost

### ISSUE THREAD

**Issue by SahilChambyal** [GadgetGoblins/Main#3]
There is an issue in styles.css file where in categories sub section, I have been unable to implement changes to google fonts icons when deployed even though its working fine in localhost.

**Comment by ashgagan** [comment]
Which font do you want??  the font in the file is working
<img width="371" alt="Screenshot 2024-02-05 at 1 36 38 PM" src="https://github.com/GadgetGoblins/Main/assets/
<img width="431" alt="Screenshot 2024-02-05 at 1 37 40 PM" src="https://github.com/GadgetGoblins/Main/assets/110713113/6ffa7ec7-bc95-41f3-b593-baf17f2b2c99">
110713113/805f2c22-6510-48c0-af78-2d52c57ed4e9">

**Comment by SahilChambyal** [comment]
Working Now, Guess it was a CDN hot-reload problem
